// For conditions of distribution and use, see copyright notice in LICENSE
// This file has been autogenerated with BindingsGenerator

#include "StableHeaders.h"
#include "BindingsHelpers.h"
#include "Geometry/Sphere.h"
#include "Math/float3x3.h"
#include "Math/float3x4.h"
#include "Math/float4x4.h"
#include "Math/Quat.h"
#include "Geometry/AABB.h"
#include "Geometry/LineSegment.h"
#include "Geometry/Triangle.h"
#include "Geometry/OBB.h"
#include "Geometry/Frustum.h"
#include "Geometry/Capsule.h"
#include "Geometry/Plane.h"
#include "Geometry/Ray.h"
#include "Geometry/Line.h"
#include "Geometry/Circle.h"
#include "Algorithm/Random/LCG.h"
#include "Math/float2.h"

namespace JSBindings
{

extern const char* float3x3_Id;
extern const char* float3x4_Id;
extern const char* float4x4_Id;
extern const char* Quat_Id;
extern const char* AABB_Id;
extern const char* LineSegment_Id;
extern const char* Triangle_Id;
extern const char* OBB_Id;
extern const char* Frustum_Id;
extern const char* Capsule_Id;
extern const char* Plane_Id;
extern const char* Ray_Id;
extern const char* Line_Id;
extern const char* Circle_Id;
extern const char* LCG_Id;
extern const char* float2_Id;

duk_ret_t float3x3_Dtor(duk_context* ctx);
duk_ret_t float3x4_Dtor(duk_context* ctx);
duk_ret_t float4x4_Dtor(duk_context* ctx);
duk_ret_t Quat_Dtor(duk_context* ctx);
duk_ret_t AABB_Dtor(duk_context* ctx);
duk_ret_t LineSegment_Dtor(duk_context* ctx);
duk_ret_t Triangle_Dtor(duk_context* ctx);
duk_ret_t OBB_Dtor(duk_context* ctx);
duk_ret_t Frustum_Dtor(duk_context* ctx);
duk_ret_t Capsule_Dtor(duk_context* ctx);
duk_ret_t Plane_Dtor(duk_context* ctx);
duk_ret_t Ray_Dtor(duk_context* ctx);
duk_ret_t Line_Dtor(duk_context* ctx);
duk_ret_t Circle_Dtor(duk_context* ctx);
duk_ret_t LCG_Dtor(duk_context* ctx);
duk_ret_t float2_Dtor(duk_context* ctx);

const char* Sphere_Id = "Sphere";

duk_ret_t Sphere_Dtor(duk_context* ctx)
{
    Sphere* obj = GetObject<Sphere>(ctx, 0, Sphere_Id);
    if (obj)
    {
        delete obj;
        SetObject(ctx, 0, 0, Sphere_Id);
    }
    return 0;
}

static duk_ret_t Sphere_Set_r(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    float r = (float)duk_require_number(ctx, 0);
    thisObj->r = r;
    return 0;
}

static duk_ret_t Sphere_Get_r(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    duk_push_number(ctx, thisObj->r);
    return 1;
}

static duk_ret_t Sphere_Ctor(duk_context* ctx)
{
    Sphere* newObj = new Sphere();
    duk_push_this(ctx); SetObject(ctx, -1, newObj, Sphere_Id); duk_push_c_function(ctx, Sphere_Dtor, 1); duk_set_finalizer(ctx, -2);
    return 0;
}

static duk_ret_t Sphere_Transform_float3x3(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    float3x3* transform = GetObject<float3x3>(ctx, 0, float3x3_Id); if (!transform) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null or invalid object argument");
    thisObj->Transform(*transform);
    return 0;
}

static duk_ret_t Sphere_Transform_float3x4(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    float3x4* transform = GetObject<float3x4>(ctx, 0, float3x4_Id); if (!transform) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null or invalid object argument");
    thisObj->Transform(*transform);
    return 0;
}

static duk_ret_t Sphere_Transform_float4x4(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    float4x4* transform = GetObject<float4x4>(ctx, 0, float4x4_Id); if (!transform) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null or invalid object argument");
    thisObj->Transform(*transform);
    return 0;
}

static duk_ret_t Sphere_Transform_Quat(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    Quat* transform = GetObject<Quat>(ctx, 0, Quat_Id); if (!transform) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null or invalid object argument");
    thisObj->Transform(*transform);
    return 0;
}

static duk_ret_t Sphere_MinimalEnclosingAABB(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    AABB ret = thisObj->MinimalEnclosingAABB();
    duk_push_object(ctx); SetObject(ctx, -1, new AABB(ret), AABB_Id); duk_push_c_function(ctx, AABB_Dtor, 1); duk_set_finalizer(ctx, -2); duk_get_global_string(ctx, AABB_Id); duk_get_prop_string(ctx, -1, "prototype"); duk_set_prototype(ctx, -3); duk_pop(ctx);
    return 1;
}

static duk_ret_t Sphere_MaximalContainedAABB(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    AABB ret = thisObj->MaximalContainedAABB();
    duk_push_object(ctx); SetObject(ctx, -1, new AABB(ret), AABB_Id); duk_push_c_function(ctx, AABB_Dtor, 1); duk_set_finalizer(ctx, -2); duk_get_global_string(ctx, AABB_Id); duk_get_prop_string(ctx, -1, "prototype"); duk_set_prototype(ctx, -3); duk_pop(ctx);
    return 1;
}

static duk_ret_t Sphere_SetNegativeInfinity(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    thisObj->SetNegativeInfinity();
    return 0;
}

static duk_ret_t Sphere_Volume(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    float ret = thisObj->Volume();
    duk_push_number(ctx, ret);
    return 1;
}

static duk_ret_t Sphere_SurfaceArea(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    float ret = thisObj->SurfaceArea();
    duk_push_number(ctx, ret);
    return 1;
}

static duk_ret_t Sphere_Diameter(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    float ret = thisObj->Diameter();
    duk_push_number(ctx, ret);
    return 1;
}

static duk_ret_t Sphere_IsFinite(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    bool ret = thisObj->IsFinite();
    duk_push_boolean(ctx, ret);
    return 1;
}

static duk_ret_t Sphere_IsDegenerate(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    bool ret = thisObj->IsDegenerate();
    duk_push_boolean(ctx, ret);
    return 1;
}

static duk_ret_t Sphere_SetDegenerate(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    thisObj->SetDegenerate();
    return 0;
}

static duk_ret_t Sphere_Contains_LineSegment(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    LineSegment* lineSegment = GetObject<LineSegment>(ctx, 0, LineSegment_Id); if (!lineSegment) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null or invalid object argument");
    bool ret = thisObj->Contains(*lineSegment);
    duk_push_boolean(ctx, ret);
    return 1;
}

static duk_ret_t Sphere_Contains_Triangle(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    Triangle* triangle = GetObject<Triangle>(ctx, 0, Triangle_Id); if (!triangle) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null or invalid object argument");
    bool ret = thisObj->Contains(*triangle);
    duk_push_boolean(ctx, ret);
    return 1;
}

static duk_ret_t Sphere_Contains_AABB(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    AABB* aabb = GetObject<AABB>(ctx, 0, AABB_Id); if (!aabb) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null or invalid object argument");
    bool ret = thisObj->Contains(*aabb);
    duk_push_boolean(ctx, ret);
    return 1;
}

static duk_ret_t Sphere_Contains_OBB(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    OBB* obb = GetObject<OBB>(ctx, 0, OBB_Id); if (!obb) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null or invalid object argument");
    bool ret = thisObj->Contains(*obb);
    duk_push_boolean(ctx, ret);
    return 1;
}

static duk_ret_t Sphere_Contains_Frustum(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    Frustum* frustum = GetObject<Frustum>(ctx, 0, Frustum_Id); if (!frustum) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null or invalid object argument");
    bool ret = thisObj->Contains(*frustum);
    duk_push_boolean(ctx, ret);
    return 1;
}

static duk_ret_t Sphere_Contains_Sphere(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    Sphere* sphere = GetObject<Sphere>(ctx, 0, Sphere_Id); if (!sphere) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null or invalid object argument");
    bool ret = thisObj->Contains(*sphere);
    duk_push_boolean(ctx, ret);
    return 1;
}

static duk_ret_t Sphere_Contains_Sphere_float(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    Sphere* sphere = GetObject<Sphere>(ctx, 0, Sphere_Id); if (!sphere) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null or invalid object argument");
    float epsilon = (float)duk_require_number(ctx, 1);
    bool ret = thisObj->Contains(*sphere, epsilon);
    duk_push_boolean(ctx, ret);
    return 1;
}

static duk_ret_t Sphere_Contains_Capsule(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    Capsule* capsule = GetObject<Capsule>(ctx, 0, Capsule_Id); if (!capsule) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null or invalid object argument");
    bool ret = thisObj->Contains(*capsule);
    duk_push_boolean(ctx, ret);
    return 1;
}

static duk_ret_t Sphere_Distance_Sphere(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    Sphere* sphere = GetObject<Sphere>(ctx, 0, Sphere_Id); if (!sphere) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null or invalid object argument");
    float ret = thisObj->Distance(*sphere);
    duk_push_number(ctx, ret);
    return 1;
}

static duk_ret_t Sphere_Distance_Capsule(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    Capsule* capsule = GetObject<Capsule>(ctx, 0, Capsule_Id); if (!capsule) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null or invalid object argument");
    float ret = thisObj->Distance(*capsule);
    duk_push_number(ctx, ret);
    return 1;
}

static duk_ret_t Sphere_Distance_AABB(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    AABB* aabb = GetObject<AABB>(ctx, 0, AABB_Id); if (!aabb) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null or invalid object argument");
    float ret = thisObj->Distance(*aabb);
    duk_push_number(ctx, ret);
    return 1;
}

static duk_ret_t Sphere_Distance_OBB(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    OBB* obb = GetObject<OBB>(ctx, 0, OBB_Id); if (!obb) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null or invalid object argument");
    float ret = thisObj->Distance(*obb);
    duk_push_number(ctx, ret);
    return 1;
}

static duk_ret_t Sphere_Distance_Plane(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    Plane* plane = GetObject<Plane>(ctx, 0, Plane_Id); if (!plane) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null or invalid object argument");
    float ret = thisObj->Distance(*plane);
    duk_push_number(ctx, ret);
    return 1;
}

static duk_ret_t Sphere_Distance_Triangle(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    Triangle* triangle = GetObject<Triangle>(ctx, 0, Triangle_Id); if (!triangle) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null or invalid object argument");
    float ret = thisObj->Distance(*triangle);
    duk_push_number(ctx, ret);
    return 1;
}

static duk_ret_t Sphere_Distance_Ray(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    Ray* ray = GetObject<Ray>(ctx, 0, Ray_Id); if (!ray) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null or invalid object argument");
    float ret = thisObj->Distance(*ray);
    duk_push_number(ctx, ret);
    return 1;
}

static duk_ret_t Sphere_Distance_Line(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    Line* line = GetObject<Line>(ctx, 0, Line_Id); if (!line) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null or invalid object argument");
    float ret = thisObj->Distance(*line);
    duk_push_number(ctx, ret);
    return 1;
}

static duk_ret_t Sphere_Distance_LineSegment(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    LineSegment* lineSegment = GetObject<LineSegment>(ctx, 0, LineSegment_Id); if (!lineSegment) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null or invalid object argument");
    float ret = thisObj->Distance(*lineSegment);
    duk_push_number(ctx, ret);
    return 1;
}

static duk_ret_t Sphere_Intersects_Plane(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    Plane* plane = GetObject<Plane>(ctx, 0, Plane_Id); if (!plane) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null or invalid object argument");
    bool ret = thisObj->Intersects(*plane);
    duk_push_boolean(ctx, ret);
    return 1;
}

static duk_ret_t Sphere_Intersects_Capsule(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    Capsule* capsule = GetObject<Capsule>(ctx, 0, Capsule_Id); if (!capsule) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null or invalid object argument");
    bool ret = thisObj->Intersects(*capsule);
    duk_push_boolean(ctx, ret);
    return 1;
}

static duk_ret_t Sphere_Intersects_Frustum(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    Frustum* frustum = GetObject<Frustum>(ctx, 0, Frustum_Id); if (!frustum) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null or invalid object argument");
    bool ret = thisObj->Intersects(*frustum);
    duk_push_boolean(ctx, ret);
    return 1;
}

static duk_ret_t Sphere_Intersects_Sphere(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    Sphere* sphere = GetObject<Sphere>(ctx, 0, Sphere_Id); if (!sphere) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null or invalid object argument");
    bool ret = thisObj->Intersects(*sphere);
    duk_push_boolean(ctx, ret);
    return 1;
}

static duk_ret_t Sphere_Intersect_Plane(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    Plane* plane = GetObject<Plane>(ctx, 0, Plane_Id); if (!plane) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null or invalid object argument");
    Circle ret = thisObj->Intersect(*plane);
    duk_push_object(ctx); SetObject(ctx, -1, new Circle(ret), Circle_Id); duk_push_c_function(ctx, Circle_Dtor, 1); duk_set_finalizer(ctx, -2); duk_get_global_string(ctx, Circle_Id); duk_get_prop_string(ctx, -1, "prototype"); duk_set_prototype(ctx, -3); duk_pop(ctx);
    return 1;
}

static duk_ret_t Sphere_Enclose_LineSegment(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    LineSegment* lineSegment = GetObject<LineSegment>(ctx, 0, LineSegment_Id); if (!lineSegment) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null or invalid object argument");
    thisObj->Enclose(*lineSegment);
    return 0;
}

static duk_ret_t Sphere_Enclose_AABB(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    AABB* aabb = GetObject<AABB>(ctx, 0, AABB_Id); if (!aabb) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null or invalid object argument");
    thisObj->Enclose(*aabb);
    return 0;
}

static duk_ret_t Sphere_Enclose_OBB(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    OBB* obb = GetObject<OBB>(ctx, 0, OBB_Id); if (!obb) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null or invalid object argument");
    thisObj->Enclose(*obb);
    return 0;
}

static duk_ret_t Sphere_Enclose_Sphere(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    Sphere* sphere = GetObject<Sphere>(ctx, 0, Sphere_Id); if (!sphere) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null or invalid object argument");
    thisObj->Enclose(*sphere);
    return 0;
}

static duk_ret_t Sphere_Enclose_Triangle(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    Triangle* triangle = GetObject<Triangle>(ctx, 0, Triangle_Id); if (!triangle) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null or invalid object argument");
    thisObj->Enclose(*triangle);
    return 0;
}

static duk_ret_t Sphere_Enclose_Frustum(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    Frustum* frustum = GetObject<Frustum>(ctx, 0, Frustum_Id); if (!frustum) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null or invalid object argument");
    thisObj->Enclose(*frustum);
    return 0;
}

static duk_ret_t Sphere_Enclose_Capsule(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    Capsule* capsule = GetObject<Capsule>(ctx, 0, Capsule_Id); if (!capsule) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null or invalid object argument");
    thisObj->Enclose(*capsule);
    return 0;
}

static duk_ret_t Sphere_ExtendRadiusToContain_Sphere_float(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    Sphere* sphere = GetObject<Sphere>(ctx, 0, Sphere_Id); if (!sphere) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null or invalid object argument");
    float epsilon = (float)duk_require_number(ctx, 1);
    thisObj->ExtendRadiusToContain(*sphere, epsilon);
    return 0;
}

static duk_ret_t Sphere_Equals_Sphere_float(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    Sphere* rhs = GetObject<Sphere>(ctx, 0, Sphere_Id); if (!rhs) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null or invalid object argument");
    float epsilon = (float)duk_require_number(ctx, 1);
    bool ret = thisObj->Equals(*rhs, epsilon);
    duk_push_boolean(ctx, ret);
    return 1;
}

static duk_ret_t Sphere_BitEquals_Sphere(duk_context* ctx)
{
    Sphere* thisObj = GetThisObject<Sphere>(ctx, Sphere_Id); if (!thisObj) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null this pointer");
    Sphere* other = GetObject<Sphere>(ctx, 0, Sphere_Id); if (!other) duk_error(ctx, DUK_ERR_REFERENCE_ERROR, "Null or invalid object argument");
    bool ret = thisObj->BitEquals(*other);
    duk_push_boolean(ctx, ret);
    return 1;
}

static duk_ret_t Sphere_Transform_Selector(duk_context* ctx)
{
    int numArgs = duk_get_top(ctx);
    if (numArgs == 1 && GetObject<float3x3>(ctx, 0, float3x3_Id))
        return Sphere_Transform_float3x3(ctx);
    if (numArgs == 1 && GetObject<float3x4>(ctx, 0, float3x4_Id))
        return Sphere_Transform_float3x4(ctx);
    if (numArgs == 1 && GetObject<float4x4>(ctx, 0, float4x4_Id))
        return Sphere_Transform_float4x4(ctx);
    if (numArgs == 1 && GetObject<Quat>(ctx, 0, Quat_Id))
        return Sphere_Transform_Quat(ctx);
    duk_error(ctx, DUK_ERR_ERROR, "Could not select function overload");
}

static duk_ret_t Sphere_Contains_Selector(duk_context* ctx)
{
    int numArgs = duk_get_top(ctx);
    if (numArgs == 1 && GetObject<LineSegment>(ctx, 0, LineSegment_Id))
        return Sphere_Contains_LineSegment(ctx);
    if (numArgs == 1 && GetObject<Triangle>(ctx, 0, Triangle_Id))
        return Sphere_Contains_Triangle(ctx);
    if (numArgs == 1 && GetObject<AABB>(ctx, 0, AABB_Id))
        return Sphere_Contains_AABB(ctx);
    if (numArgs == 1 && GetObject<OBB>(ctx, 0, OBB_Id))
        return Sphere_Contains_OBB(ctx);
    if (numArgs == 1 && GetObject<Frustum>(ctx, 0, Frustum_Id))
        return Sphere_Contains_Frustum(ctx);
    if (numArgs == 1 && GetObject<Sphere>(ctx, 0, Sphere_Id))
        return Sphere_Contains_Sphere(ctx);
    if (numArgs == 2 && GetObject<Sphere>(ctx, 0, Sphere_Id) && duk_is_number(ctx, 1))
        return Sphere_Contains_Sphere_float(ctx);
    if (numArgs == 1 && GetObject<Capsule>(ctx, 0, Capsule_Id))
        return Sphere_Contains_Capsule(ctx);
    duk_error(ctx, DUK_ERR_ERROR, "Could not select function overload");
}

static duk_ret_t Sphere_Distance_Selector(duk_context* ctx)
{
    int numArgs = duk_get_top(ctx);
    if (numArgs == 1 && GetObject<Sphere>(ctx, 0, Sphere_Id))
        return Sphere_Distance_Sphere(ctx);
    if (numArgs == 1 && GetObject<Capsule>(ctx, 0, Capsule_Id))
        return Sphere_Distance_Capsule(ctx);
    if (numArgs == 1 && GetObject<AABB>(ctx, 0, AABB_Id))
        return Sphere_Distance_AABB(ctx);
    if (numArgs == 1 && GetObject<OBB>(ctx, 0, OBB_Id))
        return Sphere_Distance_OBB(ctx);
    if (numArgs == 1 && GetObject<Plane>(ctx, 0, Plane_Id))
        return Sphere_Distance_Plane(ctx);
    if (numArgs == 1 && GetObject<Triangle>(ctx, 0, Triangle_Id))
        return Sphere_Distance_Triangle(ctx);
    if (numArgs == 1 && GetObject<Ray>(ctx, 0, Ray_Id))
        return Sphere_Distance_Ray(ctx);
    if (numArgs == 1 && GetObject<Line>(ctx, 0, Line_Id))
        return Sphere_Distance_Line(ctx);
    if (numArgs == 1 && GetObject<LineSegment>(ctx, 0, LineSegment_Id))
        return Sphere_Distance_LineSegment(ctx);
    duk_error(ctx, DUK_ERR_ERROR, "Could not select function overload");
}

static duk_ret_t Sphere_Intersects_Selector(duk_context* ctx)
{
    int numArgs = duk_get_top(ctx);
    if (numArgs == 1 && GetObject<Plane>(ctx, 0, Plane_Id))
        return Sphere_Intersects_Plane(ctx);
    if (numArgs == 1 && GetObject<Capsule>(ctx, 0, Capsule_Id))
        return Sphere_Intersects_Capsule(ctx);
    if (numArgs == 1 && GetObject<Frustum>(ctx, 0, Frustum_Id))
        return Sphere_Intersects_Frustum(ctx);
    if (numArgs == 1 && GetObject<Sphere>(ctx, 0, Sphere_Id))
        return Sphere_Intersects_Sphere(ctx);
    duk_error(ctx, DUK_ERR_ERROR, "Could not select function overload");
}

static duk_ret_t Sphere_Enclose_Selector(duk_context* ctx)
{
    int numArgs = duk_get_top(ctx);
    if (numArgs == 1 && GetObject<LineSegment>(ctx, 0, LineSegment_Id))
        return Sphere_Enclose_LineSegment(ctx);
    if (numArgs == 1 && GetObject<AABB>(ctx, 0, AABB_Id))
        return Sphere_Enclose_AABB(ctx);
    if (numArgs == 1 && GetObject<OBB>(ctx, 0, OBB_Id))
        return Sphere_Enclose_OBB(ctx);
    if (numArgs == 1 && GetObject<Sphere>(ctx, 0, Sphere_Id))
        return Sphere_Enclose_Sphere(ctx);
    if (numArgs == 1 && GetObject<Triangle>(ctx, 0, Triangle_Id))
        return Sphere_Enclose_Triangle(ctx);
    if (numArgs == 1 && GetObject<Frustum>(ctx, 0, Frustum_Id))
        return Sphere_Enclose_Frustum(ctx);
    if (numArgs == 1 && GetObject<Capsule>(ctx, 0, Capsule_Id))
        return Sphere_Enclose_Capsule(ctx);
    duk_error(ctx, DUK_ERR_ERROR, "Could not select function overload");
}

static const duk_function_list_entry Sphere_Functions[] = {
    {"Transform", Sphere_Transform_Selector, DUK_VARARGS}
    ,{"MinimalEnclosingAABB", Sphere_MinimalEnclosingAABB, 0}
    ,{"MaximalContainedAABB", Sphere_MaximalContainedAABB, 0}
    ,{"SetNegativeInfinity", Sphere_SetNegativeInfinity, 0}
    ,{"Volume", Sphere_Volume, 0}
    ,{"SurfaceArea", Sphere_SurfaceArea, 0}
    ,{"Diameter", Sphere_Diameter, 0}
    ,{"IsFinite", Sphere_IsFinite, 0}
    ,{"IsDegenerate", Sphere_IsDegenerate, 0}
    ,{"SetDegenerate", Sphere_SetDegenerate, 0}
    ,{"Contains", Sphere_Contains_Selector, DUK_VARARGS}
    ,{"Distance", Sphere_Distance_Selector, DUK_VARARGS}
    ,{"Intersects", Sphere_Intersects_Selector, DUK_VARARGS}
    ,{"Intersect", Sphere_Intersect_Plane, 1}
    ,{"Enclose", Sphere_Enclose_Selector, DUK_VARARGS}
    ,{"ExtendRadiusToContain", Sphere_ExtendRadiusToContain_Sphere_float, 2}
    ,{"Equals", Sphere_Equals_Sphere_float, 2}
    ,{"BitEquals", Sphere_BitEquals_Sphere, 1}
    ,{nullptr, nullptr, 0}
};

void Expose_Sphere(duk_context* ctx)
{
    duk_push_c_function(ctx, Sphere_Ctor, DUK_VARARGS);
    duk_push_object(ctx);
    duk_put_function_list(ctx, -1, Sphere_Functions);
    DefineProperty(ctx, "r", Sphere_Get_r, Sphere_Set_r);
    duk_put_prop_string(ctx, -2, "prototype");
    duk_put_global_string(ctx, Sphere_Id);
}

}
