// For conditions of distribution and use, see copyright notice in LICENSE
// This file has been autogenerated with BindingsGenerator

#include "StableHeaders.h"
#include "CoreTypes.h"
#include "JavaScriptInstance.h"
#include "LoggingFunctions.h"
#include "Framework/Framework.h"

#ifdef _MSC_VER
#pragma warning(disable: 4800)
#endif

#include "Framework/ConfigAPI.h"
#include "Framework/FrameAPI.h"
#include "Scene/SceneAPI.h"
#include "Asset/AssetAPI.h"


using namespace Tundra;
using namespace std;

namespace JSBindings
{



static const char* Framework_ID = "Framework";

const char* SignalWrapper_Framework_ExitRequested_ID = "SignalWrapper_Framework_ExitRequested";

class SignalWrapper_Framework_ExitRequested
{
public:
    SignalWrapper_Framework_ExitRequested(Object* owner, Signal0< void >* signal) :
        owner_(owner),
        signal_(signal)
    {
    }

    WeakPtr<Object> owner_;
    Signal0< void >* signal_;
};

class SignalReceiver_Framework_ExitRequested : public SignalReceiver
{
public:
    void OnSignal()
    {
        duk_context* ctx = ctx_;
        duk_push_global_object(ctx);
        duk_get_prop_string(ctx, -1, "_OnSignal");
        duk_remove(ctx, -2);
        duk_push_number(ctx, (size_t)key_);
        duk_push_array(ctx);
        bool success = duk_pcall(ctx, 2) == 0;
        if (!success) LogError("[JavaScript] OnSignal: " + String(duk_safe_to_string(ctx, -1)));
        duk_pop(ctx);
    }
};

static duk_ret_t SignalWrapper_Framework_ExitRequested_Finalizer(duk_context* ctx)
{
    FinalizeValueObject<SignalWrapper_Framework_ExitRequested>(ctx, SignalWrapper_Framework_ExitRequested_ID);
    return 0;
}

static duk_ret_t SignalWrapper_Framework_ExitRequested_Connect(duk_context* ctx)
{
    SignalWrapper_Framework_ExitRequested* wrapper = GetThisValueObject<SignalWrapper_Framework_ExitRequested>(ctx, SignalWrapper_Framework_ExitRequested_ID);
    if (!wrapper->owner_) return 0;
    HashMap<void*, SharedPtr<SignalReceiver> >& signalReceivers = JavaScriptInstance::InstanceFromContext(ctx)->SignalReceivers();
    if (signalReceivers.Find(wrapper->signal_) == signalReceivers.End())
    {
        SignalReceiver_Framework_ExitRequested* receiver = new SignalReceiver_Framework_ExitRequested();
        receiver->ctx_ = ctx;
        receiver->key_ = wrapper->signal_;
        wrapper->signal_->Connect(receiver, &SignalReceiver_Framework_ExitRequested::OnSignal);
        signalReceivers[wrapper->signal_] = receiver;
    }
    CallConnectSignal(ctx, wrapper->signal_);
    return 0;
}

static duk_ret_t SignalWrapper_Framework_ExitRequested_Disconnect(duk_context* ctx)
{
    SignalWrapper_Framework_ExitRequested* wrapper = GetThisValueObject<SignalWrapper_Framework_ExitRequested>(ctx, SignalWrapper_Framework_ExitRequested_ID);
    if (!wrapper->owner_) return 0;
    CallDisconnectSignal(ctx, wrapper->signal_);
    return 0;
}

static duk_ret_t SignalWrapper_Framework_ExitRequested_Emit(duk_context* ctx)
{
    SignalWrapper_Framework_ExitRequested* wrapper = GetThisValueObject<SignalWrapper_Framework_ExitRequested>(ctx, SignalWrapper_Framework_ExitRequested_ID);
    if (!wrapper->owner_) return 0;
    wrapper->signal_->Emit();
    return 0;
}

static duk_ret_t Framework_Get_ExitRequested(duk_context* ctx)
{
    Framework* thisObj = GetThisWeakObject<Framework>(ctx);
    SignalWrapper_Framework_ExitRequested* wrapper = new SignalWrapper_Framework_ExitRequested(thisObj, &thisObj->ExitRequested);
    PushValueObject(ctx, wrapper, SignalWrapper_Framework_ExitRequested_ID, SignalWrapper_Framework_ExitRequested_Finalizer, false);
    duk_push_c_function(ctx, SignalWrapper_Framework_ExitRequested_Connect, DUK_VARARGS);
    duk_put_prop_string(ctx, -2, "Connect");
    duk_push_c_function(ctx, SignalWrapper_Framework_ExitRequested_Disconnect, DUK_VARARGS);
    duk_put_prop_string(ctx, -2, "Disconnect");
    duk_push_c_function(ctx, SignalWrapper_Framework_ExitRequested_Emit, 0);
    duk_put_prop_string(ctx, -2, "Emit");
    return 1;
}

static duk_ret_t Framework_ParseWildCardFilename_String(duk_context* ctx)
{
    Framework* thisObj = GetThisWeakObject<Framework>(ctx);
    String input = duk_require_string(ctx, 0);
    String ret = thisObj->ParseWildCardFilename(input);
    duk_push_string(ctx, ret.CString());
    return 1;
}

static duk_ret_t Framework_HasCommandLineParameter_String(duk_context* ctx)
{
    Framework* thisObj = GetThisWeakObject<Framework>(ctx);
    String value = duk_require_string(ctx, 0);
    bool ret = thisObj->HasCommandLineParameter(value);
    duk_push_boolean(ctx, ret);
    return 1;
}

static duk_ret_t Framework_CommandLineParameters_String(duk_context* ctx)
{
    Framework* thisObj = GetThisWeakObject<Framework>(ctx);
    String key = duk_require_string(ctx, 0);
    Vector< String > ret = thisObj->CommandLineParameters(key);
    PushStringVector(ctx, ret);
    return 1;
}

static duk_ret_t Framework_ConfigFiles(duk_context* ctx)
{
    Framework* thisObj = GetThisWeakObject<Framework>(ctx);
    Vector< String > ret = thisObj->ConfigFiles();
    PushStringVector(ctx, ret);
    return 1;
}

static duk_ret_t Framework_Exit(duk_context* ctx)
{
    Framework* thisObj = GetThisWeakObject<Framework>(ctx);
    thisObj->Exit();
    return 0;
}

static duk_ret_t Framework_ForceExit(duk_context* ctx)
{
    Framework* thisObj = GetThisWeakObject<Framework>(ctx);
    thisObj->ForceExit();
    return 0;
}

static duk_ret_t Framework_CancelExit(duk_context* ctx)
{
    Framework* thisObj = GetThisWeakObject<Framework>(ctx);
    thisObj->CancelExit();
    return 0;
}

static duk_ret_t Framework_IsHeadless(duk_context* ctx)
{
    Framework* thisObj = GetThisWeakObject<Framework>(ctx);
    bool ret = thisObj->IsHeadless();
    duk_push_boolean(ctx, ret);
    return 1;
}

static duk_ret_t Framework_Config(duk_context* ctx)
{
    Framework* thisObj = GetThisWeakObject<Framework>(ctx);
    ConfigAPI * ret = thisObj->Config();
    PushWeakObject(ctx, ret);
    return 1;
}

static duk_ret_t Framework_Frame(duk_context* ctx)
{
    Framework* thisObj = GetThisWeakObject<Framework>(ctx);
    FrameAPI * ret = thisObj->Frame();
    PushWeakObject(ctx, ret);
    return 1;
}

static duk_ret_t Framework_Scene(duk_context* ctx)
{
    Framework* thisObj = GetThisWeakObject<Framework>(ctx);
    SceneAPI * ret = thisObj->Scene();
    PushWeakObject(ctx, ret);
    return 1;
}

static duk_ret_t Framework_Asset(duk_context* ctx)
{
    Framework* thisObj = GetThisWeakObject<Framework>(ctx);
    AssetAPI * ret = thisObj->Asset();
    PushWeakObject(ctx, ret);
    return 1;
}

static duk_ret_t Framework_OrganizationName_Static(duk_context* ctx)
{
    const String & ret = Framework::OrganizationName();
    duk_push_string(ctx, ret.CString());
    return 1;
}

static duk_ret_t Framework_ApplicationName_Static(duk_context* ctx)
{
    const String & ret = Framework::ApplicationName();
    duk_push_string(ctx, ret.CString());
    return 1;
}

static duk_ret_t Framework_VersionString_Static(duk_context* ctx)
{
    const String & ret = Framework::VersionString();
    duk_push_string(ctx, ret.CString());
    return 1;
}

static duk_ret_t Framework_Instance_Static(duk_context* ctx)
{
    Framework * ret = Framework::Instance();
    PushWeakObject(ctx, ret);
    return 1;
}

static const duk_function_list_entry Framework_Functions[] = {
    {"ParseWildCardFilename", Framework_ParseWildCardFilename_String, 1}
    ,{"HasCommandLineParameter", Framework_HasCommandLineParameter_String, 1}
    ,{"CommandLineParameters", Framework_CommandLineParameters_String, 1}
    ,{"ConfigFiles", Framework_ConfigFiles, 0}
    ,{"Exit", Framework_Exit, 0}
    ,{"ForceExit", Framework_ForceExit, 0}
    ,{"CancelExit", Framework_CancelExit, 0}
    ,{"IsHeadless", Framework_IsHeadless, 0}
    ,{"Config", Framework_Config, 0}
    ,{"Frame", Framework_Frame, 0}
    ,{"Scene", Framework_Scene, 0}
    ,{"Asset", Framework_Asset, 0}
    ,{nullptr, nullptr, 0}
};

static const duk_function_list_entry Framework_StaticFunctions[] = {
    {"OrganizationName", Framework_OrganizationName_Static, 0}
    ,{"ApplicationName", Framework_ApplicationName_Static, 0}
    ,{"VersionString", Framework_VersionString_Static, 0}
    ,{"Instance", Framework_Instance_Static, 0}
    ,{nullptr, nullptr, 0}
};

void Expose_Framework(duk_context* ctx)
{
    duk_push_object(ctx);
    duk_put_function_list(ctx, -1, Framework_StaticFunctions);
    duk_push_object(ctx);
    duk_put_function_list(ctx, -1, Framework_Functions);
    DefineProperty(ctx, "ExitRequested", Framework_Get_ExitRequested, nullptr);
    duk_put_prop_string(ctx, -2, "prototype");
    duk_put_global_string(ctx, Framework_ID);
}

}
